from enum import Enum

class TokenType(Enum):
    CONST   = "CONST"
    ADD     = "ADD"
    POP     = "POP"
    SUB     = "SUB"
    MUL     = "MUL"
    DIV     = "DIV"
    TRUE    = "TRUE"
    FALSE   = "FALSE"
    EQ      = "EQ"
    NEQ     = "NEQ"
    GT      = "GT"
    MINUS   = "MINUS"
    BANG    = "BANG"
    JUMP    = "JUMP"
    JNT     = "JNT"
    NONE    = "NONE"
    GET     = "GET"
    SET     = "SET"
    ARRAY   = "ARRAY"
    HASH    = "HASH"
    INDEX   = "INDEX"
    CALL    = "CALL"
    RETURN  = "RETURN"
    RETURNV = "RETURNV"
    GETL    = "GETL"
    SETL    = "SETL"
    BUILTIN = "BUILTIN"
    END     = "END"
